# Generated by Django 4.0.6 on 2022-07-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_attendance_present_attendance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
