# Generated by Django 4.0.6 on 2022-07-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_studentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='roll_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
